# Generated by Django 3.0.5 on 2021-11-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211029_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('W', 'Watch'), ('S', 'Sunglass')], max_length=2),
        ),
    ]
